spring:
  datasource:
    name: blog
    username: kuro
    password: kuro@Pass
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&&serverTimezone=GMT%2B8&useSSL=false
    dynamic:
      primary: mysql_dev
      strict: false
      datasource:
        mysql_dev:
          type: com.zaxxer.hikari.HikariDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/blog?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&&serverTimezone=GMT%2B8&useSSL=false
          username: kuro
          password: kuro@Pass
  resources:
    static-locations: file:/home/kuro/Pictures/blogSource/

  mvc:
    static-path-pattern: /pic/**

  servlet:
    multipart:
      #设置单个文件大小，单位MB和KB都可以
      max-file-size: 500MB
      #设置总上传的数据大小，单位MB和KB都可以
      max-request-size: 1024MB

springdoc:
  api-docs:
    #默认为true开启
    enabled: true

# Logger Config
logging:
  level:
    root: info
    com.jiayeli.blog.dao: debug
    com.baomidou.mybatisplus.samples: debug

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: classpath:com.jiayeli.blog.dao
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# MyBatis-Plus 配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: classpath:com.jiayeli.blog.dao
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false
