
spring:
  datasource:
    name: blog
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=UTF-8&&serverTimezone=GMT%2B8&useSSL=false
  resources:
    static-locations: file:d:/booksmsFiles/

  mvc:
    static-path-pattern: /pic/**

logging:
  level:
    root: info
    com.jiayeli.blog.dao: debug

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: classpath:com.jiayeli.blog.dao
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


